//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_PR16_clothes__Palashicheva.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovars
    {
        public int id { get; set; }
        public string naimenov { get; set; }
        public int kolichestvo { get; set; }
        public decimal cena { get; set; }
        public int ColorID { get; set; }
        public string sostav { get; set; }
        public string komment { get; set; }
        public int SizeID { get; set; }
        public int StranaID { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual Size Size { get; set; }
        public virtual Strana Strana { get; set; }
    }
}
